version: "3"
services:
  php-cli:
    env_file: ../../../.env
    build:
      context: ../..
      dockerfile: containers/cli/Dockerfile
    command: "php ./benchmarks.php --iter=1000"
    volumes:
      - "../../../results:/results"
